#!/bin/bash

app_name=$1

BUILD_DIR="./out/"

#
MAIN_CLASS="Main"

#
SERVER_ROUTER_CLASS="edu.kennesaw.cs4504.services.TCPServerRouter"

if [ "$app_name" = "main" ] ; then
  java -cp $BUILD_DIR $MAIN_CLASS
elif [ "$app_name" = "router" ] ; then
  echo $SERVER_ROUTER_PATH
  java -cp $BUILD_DIR $SERVER_ROUTER_CLASS
else
  echo "Could not find the program: " $app_name
fi
